### ISSUE TITLE
Add “preview”

### ISSUE THREAD

**Issue by dserban** [aelve/microlens#40]
```
over (ix 1 . ix 1) (+1) [[2,0,0,2],[0,0,0,0],[0,0,0,0],[2,0,0,2]]
```
gives back th expected result.

But in the absence of `preview` how does one retrieve the element?

**Comment by neongreen** [comment]
`preview` is `^?`, and I don't think it'll be added to `Lens.Micro` pretty much for the same reason `view` isn't there.

**Comment by dserban** [comment]
Thanks.
Spoken as someone who dislikes operators, please consider adding `preview` to `microlens-mtl` - that would be awesome.
Consider it an enhancement request.
