### ISSUE TITLE
Move descriptions of lenses and traversals into $notes

### ISSUE THREAD

**Issue by neongreen** [aelve/microlens#62]

**Comment by fosskers** [comment]
What does that do?

**Comment by neongreen** [comment]
Currently the general descriptions of lenses and traversals are placed in the documentation of `Lens` and `Traversal`, while descriptions of getters and setters are in free-floating pieces of documentation (`$setters-note`, `$getters-note`) that are placed immediately after the headings. I want to do the same thing to `Lens` and `Traversal` (for consistency).
