### ISSUE TITLE
microlens currently broken on GHC 8.0 snapshot

### ISSUE THREAD

**Issue by hvr** [aelve/microlens#63]
See also https://ghc.haskell.org/trac/ghc/ticket/11339

A sensible workaround seems to be to simply enable `{-# LANGUAGE MonoLocalBinds #-}` in `src/Lens/Micro.hs`

**Comment by neongreen** [comment]
@hvr, @goldfirere: thanks for the detective work!

Released the fix in microlens-0.4.0.1.

**Comment by hvr** [comment]
@neongreen thanks for the quick response!

btw, would you mind uploading a `microlens-0.3.5.1` fix as well for the benefit of packages having a `microlens == 0.3.*` bound? 

See http://matrix.hackage.haskell.org/package/microlens for current situation

**Comment by neongreen** [comment]
Done.
