### ISSUE TITLE
Lens.Micro.Platform doesn't export `strictText`, etc

### ISSUE THREAD

**Issue by fosskers** [aelve/microlens#64]
It would be very handy to have these available.

**Comment by neongreen** [comment]
Okay, I'll add:

* `strict`, `lazy`
* `packed`, `unpacked`
* `bytes`, `chars`, `packedBytes`/`Chars`, `unpackedBytes`/`Chars`

Is there anything else you had in mind?

**Comment by neongreen** [comment]
Oh, I just noticed that there's actual `strictText` in `Lens/Micro/Platform.hs`. It can't be exported because it's not exported from lens either (but I don't see why you would need it when you have `each` – so, can you explain?).

**Comment by fosskers** [comment]
Oh, I was just looking for a way to traverse `Text` and `ByteString`, didn't know `each` worked.

**Comment by fosskers** [comment]
I'd almost say you could take those changes back out, to avoid `transformers`.

**Comment by neongreen** [comment]
transformers is shipped with GHC, so it should be okay for microlens-ghc to depend on it.

**Comment by fosskers** [comment]
Ah ok.

Actually, there's another problem now: the `Each` instance for the `ByteString` types in `microlens-ghc` is for `Word8`, not the `Char` that I'd need.

The `Word8 -> Char` conversion is available via `Data.Text.Internal.Unsafe.Char.unsafeChr8`, but I'd rather not use that.

**Comment by neongreen** [comment]
That's what [`chars`](http://hackage.haskell.org/package/lens-4.13/docs/Data-ByteString-Lazy-Lens.html#v:chars) is for (I haven't added it yet, but it's on the list).

**Comment by fosskers** [comment]
That seems to be for the `Lazy` variant only. I could leave out the `Strict` instance that I'm deriving in my own library, I suppose, but I'd like to have all of them.

**Comment by neongreen** [comment]
Sorry, wrong link. This [`chars`](http://hackage.haskell.org/package/lens-4.13/docs/Data-ByteString-Lens.html#v:chars) works for both strict and lazy bytestrings.

**Comment by fosskers** [comment]
Roger, that looks good.

**Comment by neongreen** [comment]
I just released microlens-platform-0.2.1.0 that includes `chars`.

**Comment by fosskers** [comment]
Great, thanks.
