### ISSUE TITLE
Sexier way to traverse Text?

### ISSUE THREAD

**Issue by fosskers** [aelve/microlens#70]
In `microlens-platform` we see:

```haskell
instance (a ~ Char, b ~ Char) => Each TL.Text TL.Text a b where
  each = lazyText

lazyUnpacked :: Lens' TL.Text String
lazyUnpacked f t = TL.pack <$> f (TL.unpack t)

lazyText :: Traversal' TL.Text Char
lazyText = lazyUnpacked . traversed
```
Where we see an internal conversion to `String` when using `each`. Is it possible to avoid this, or will compilation with `-O2` etc just Do-The-Right-Thing™ and avoid wasted computation?

**Comment by neongreen** [comment]
Compilation with `-O` will do the right thing only if you're using the traversal as a map or a getter, thanks to [some `RULES`](https://github.com/aelve/microlens/blob/master/microlens-platform/src/Lens/Micro/Platform.hs#L268) in `Lens.Micro.Platform`. If you're actually traversing the `Text` (as in e.g. `each :: (Char -> IO Char) -> Text -> IO Text)`), there won't be any benefit.

**Comment by neongreen** [comment]
lens (and conversely microlens) is more clever about traversing e.g. `ByteString` (see [here](https://github.com/aelve/microlens/blob/master/microlens-ghc/src/Lens/Micro/GHC/Internal.hs#L184)), but there's no custom traversal for `Text`, and I don't feel confident enough about low-level workings of `Text` to try to write one.

**Comment by fosskers** [comment]
I would be traversing the `Text` as a map, with some function `foo :: Char -> Blah`. What I'd like is:

```haskell
bar :: Text -> [Blah]
bar t = t ^.. each . to foo
```

**Comment by neongreen** [comment]
Here's a small benchmark that shows that `each` gets optimised better than `unpacked . traversed` in your situation:

~~~ haskell
import Lens.Micro.Platform
import Criterion.Main
import Criterion
import qualified Data.Text.Lazy as TL

main = defaultMain [
  bench "native" $ nf barNative longText,
  bench "good"   $ nf bar longText,
  bench "bad"    $ nf barBad longText ]

longText :: TL.Text
longText = TL.replicate 1000000 (TL.pack "foobar")

barNative :: TL.Text -> Int
barNative = TL.foldl' (\n c -> n + fromEnum c) 0

bar :: TL.Text -> Int
bar t = sum (t ^.. each . to fromEnum)

barBad :: TL.Text -> Int
barBad t = sum (t ^.. unpacked . traversed . to fromEnum)
~~~

~~~
benchmarking native
time                 103.9 ms   (102.5 ms .. 105.0 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 104.4 ms   (103.7 ms .. 105.2 ms)
std dev              1.166 ms   (784.1 μs .. 1.615 ms)

benchmarking good
time                 118.5 ms   (118.1 ms .. 118.8 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 118.6 ms   (118.5 ms .. 118.7 ms)
std dev              209.6 μs   (120.5 μs .. 304.6 μs)
variance introduced by outliers: 11% (moderately inflated)

benchmarking bad
time                 174.0 ms   (173.3 ms .. 174.4 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 174.0 ms   (173.8 ms .. 174.3 ms)
std dev              328.8 μs   (216.7 μs .. 479.3 μs)
variance introduced by outliers: 12% (moderately inflated)
~~~

**Comment by fosskers** [comment]
A decent increase in speed, cool. Thanks for putting that together. I reran those benchmarks at each of `-O2`, `-O` and no optimization, and "good" consistently runs faster than "bad". Interestingly  enough, the "native" bench runs slower under `-O2`.
