### ISSUE TITLE
Add mapAccumLOf

### ISSUE THREAD

**Issue by tomjaguarpaw** [aelve/microlens#71]
Could we please have `mapAccumLOf`?  This is the whole implementation.  I'm happy to submit a PR if you'll guarantee to accept it.

    import           Data.Tuple                 (swap)
    import           Lens.Micro                 (LensLike)
    import           Control.Monad.State        (State, runState, state)
    
    mapAccumLOf :: LensLike (State acc) s t a b -> (acc -> a -> (acc, b)) -> acc -> s -> (acc, t)
    mapAccumLOf l f acc0 s = swap (runState (l g s) acc0) where
       g a = state $ \acc -> swap (f acc a)

**Comment by neongreen** [comment]
Sure we can! I don't mind implementing it myself, but I'm not at home right now, and so I won't be able to release a new version until the evening.

This is general enough to go to the base package. I'm not sure whether a transformers dependency will be needed or whether we can get away with the reimplementation of State we already have.

**Comment by tomjaguarpaw** [comment]
Great!

**Comment by neongreen** [comment]
Released microlens-0.4.4 and friends.
