### ISSUE TITLE
`Each` instance for `NonEmpty`

### ISSUE THREAD

**Issue by mitchellwrosen** [aelve/microlens#87]
Is there any particular reason this instance isn't provided? I'm happy to contribute a patch. Thanks!

**Comment by neongreen** [comment]
Nah, no reason. Is this instance provided in lens? If yes – sure, having a patch (for base >= 4.9, to avoid the semigroups dependency) would be nice.

**Comment by mitchellwrosen** [comment]
Yeah, the instance is provided in `lens`. Ok, patch incoming...

**Comment by neongreen** [comment]
@fosskers @mitchellwrosen Released as microlens-0.4.8.
