### ISSUE TITLE
`makeLenses` fails with associated types.

### ISSUE THREAD

**Issue by daghack** [aelve/microlens#93]
Returns the error message `makeFieldOptics: Expected type constructor name`.
A minimum example that will cause this to occur can be found [here](https://gist.github.com/daghack/2d854d0d3000c6bcb5c49000d54d4582).

**Comment by neongreen** [comment]
@daghack can you check if it works with `lens`?

If it does, we need to switch to their new TH generator and it'll work for us as well.

If it doesn't, this issue should be filed at github.com/ekmett/lens, not here.

**Comment by boj** [comment]
@neongreen I was experimenting with switching our whole code base over from lens to microlens and experienced this same exact error.

**Comment by neongreen** [comment]
Alright, I'll try to get a new version of microlens-th ready today.

**Comment by neongreen** [comment]
Fixed in microlens-th-0.4.2.

**Comment by boj** [comment]
@neongreen I feel like I wasted your time. It turns out @daghack's example has the same error I wrote in my own code. There is only a single quote in the `makeLenses 'Thing` clause vs. `makeLenses ''Thing` - which I only discovered in our own code after trying to figure out why your fix didn't work. That actually creates valid lenses with `lens` for some reason.

**Comment by neongreen** [comment]
It creates valid lenses with `lens` because otherwise you can't refer to the data family with a name. `'Thing` refers to the constructor, `''Thing` refers to the type. If your type is `DataFamily Foo`, you can't use the name-syntax to refer to it.

**Comment by boj** [comment]
Ah that makes sense, thanks for the explanation. Lens mechanics are still a bit over my head.

**Comment by neongreen** [comment]
It's not lens mechanics really, it's just a hack :) Some other libraries use the same trick (either `acid-state` or my fork of it does it, I think).

Another thing lens people could do is let stuff like `[t|DataFamily Foo|]` be passed to `makeLenses`, but it's uglier and also prevents you from passing ordinary `Name`s.
