### ISSUE TITLE
microlens-0.4.8.2 failed to build

### ISSUE THREAD

**Issue by felixonmars** [aelve/microlens#99]
I am getting the following error when trying to build microlens 0.4.8.2, which does not exist in the previous 0.4.8.1 release:

```
Configuring microlens-0.4.8.2...
Preprocessing library for microlens-0.4.8.2..
Building library for microlens-0.4.8.2..

src/Lens/Micro/Extras.hs:1:1: error:
    lexical error (UTF-8 decoding error)
  |
����������!��������������@��������������!�������mkdir foo��v��������!�������#1514824048�048�����#1514824048�
  | ^
```

**Comment by dmwit** [comment]
I've let the Hackage trustees know; they may be able to blacklist this version so that cabal doesn't choose this version for people who don't know about the problem.

https://github.com/haskell-infra/hackage-trustees/issues/123

**Comment by glguy** [comment]
After confirming that multiple .hs files were in fact binary data I've updated the constraint on this particular version to be unsatisfiable.

**Comment by dmwit** [comment]
Looks like microlens-th was also affected, so once you find the cause you may want to reupload that one as well.

**Comment by glguy** [comment]
Confirmed issue and disabled microlens-th-0.4.1.2

**Comment by hvr** [comment]
@neongreen can you tell us exactly how you generated the source-tarball for `microlens-th-0.4.1.2` and `microlens-0.4.8.2`? I would really like to know how this kind of memory-buffer corruption could have happened, which must have happened client-side, somewhere in the code-path reading the `.hs` file from the filesystem (and before it got zlib compressed).

**Comment by neongreen** [comment]
Heh. I just did `cabal sdist` and `cabal upload dist/microlens-0.4.8.2.tar.gz`.

**Comment by neongreen** [comment]
This isn't memory-buffer corruption – I checked and the file on my system is corrupted as well. The worrying thing for me is that Git reports a clean repository *and* there's no corruption in any of the commits.

**Comment by neongreen** [comment]
I think but can't prove that the cause is a crash my laptop suffered recently (after which fsck reported lots of filesystem corruption and missing files).

Alright, I have re-cloned the repo and built all packages. @hvr what should I do now? Bump .patch versions and reupload the three affected packages?

**Comment by hvr** [comment]
@neongreen I'm kinda relieved this turns out to be filesystem corruption (as it means that haskell libraries weren't at fault). And yes, just release new patch-level releases (sans corruption) of `microlens` and `microlens-th`

**Comment by neongreen** [comment]
I thouht microlens-mtl was the third package but it turned out not to be.

**Comment by neongreen** [comment]
> which file-system were you using?

ext4
